#!/bin/bash
#SBATCH -N 1
#SBATCH -t 15:00:00
#SBATCH -p genoa

#module load 2022
#module load IPython/8.5.0-GCCcore-11.3.0
#module load JupyterHub/3.0.0-GCCcore-11.3.0
cd ~
echo "into the Scripts for my project"
export PATH=/home/ybhatti/yusufb/miniconda3/bin:$PATH
source activate master

##PORT=`shuf -i 5000-5999 -n 1`
PORT=51525
#
LOGIN_HOST=${SLURM_SUBMIT_HOST}-pub.snellius.surf.nl
BATCH_HOST=$(hostname)
 
echo "To connect to the notebook type the following command from your local terminal:"
echo "ssh -N -J ${USER}@${LOGIN_HOST} ${USER}@${BATCH_HOST} -L ${PORT}:localhost:${PORT}"
echo
echo "After connection is established in your local browser go to the address:"
echo "http://localhost:${PORT}"
/usr/bin/ssh -N -f -R $PORT:localhost:$PORT snellius

echo "Connect to localhost" 
sed -i "s|^ssh -N.*|ssh -N -J ${USER}@${LOGIN_HOST} ${USER}@${BATCH_HOST} -L ${PORT}:localhost:${PORT} &|" HPC_Python/ssh_connect.sh

#ssh -N -J ${USER}@${LOGIN_HOST} ${USER}@${BATCH_HOST} -L ${PORT}:localhost:${PORT} &
echo "connected to local host ssh -N -J ${USER}@${LOGIN_HOST} ${USER}@${BATCH_HOST} -L ${PORT}:localhost:${PORT}"

jupyter-lab --no-browser --port $PORT #--NotebookApp.max_buffer_size=96636764160

#ssh -N -J ybhatti@int4-pub.snellius.surf.nl ybhatti@tcn186.local.snellius.surf.nl -L 51525:localhost:51525
