#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 26 15:19:09 2020

@author: ybh10
"""

dates=['001','032','060','091','121','152','182','213','244','274','305','335']
dates2=['031','059','090','120','151','181','212','243','273','304','334','365']
import numpy as np
import webbrowser
import requests
import urllib.request
import time
from bs4 import BeautifulSoup
import re
from datetime import timedelta, datetime
import sys

year=np.arange(2003,2020,1)
chrome_path = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s'
Data=[]
for yr in (year):
    for d,d2 in zip(dates,dates2):
        data=str(yr)+d+str(yr)+d2
        print(data)
        Data.append(data)
    
    
for D in (Data):
    files='https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A'+D+'.L3m_MO_CHL_chlor_a_9km.nc'
    print(files)
    
#for month in range(1,13):
#    print('month=',month)
#    for day in range(1,29):
#        webbrowser.get(chrome_path).open('hhttps://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20200012020031.L3m_MO_CHL_chlor_a_9km.nc.{}{:02d}{:02d}'
#                      .format(year,month,day)+'.nc')
#day=29#get the 29th        
#for month in [1,3,4,5,6,7,8,9,10,11,12]:
#    webbrowser.get(chrome_path).open('https://giovanni.gsfc.nasa.gov/session/1291D6CC-844D-11EA-8E98-595979988AF1/76EA5316-9B12-11EA-986C-D3E44B67C885/76EAFC62-9B12-11EA-986C-D3E44B67C885/g4.timeAvgMap.MYD08_D3_6_1_AOD_550_Dark_Target_Deep_Blue_Combined_Mean.{}{:02d}{:02d}'.format(year,month,day)+'-{}{:02d}{:02d}'.format(year,month,day)+'.180W_90S_180E_90N.nc')
#
#day=30#get the 30th
#for month in [1,3,4,5,6,7,8,9,10,11,12]:
#    webbrowser.get(chrome_path).open('https://giovanni.gsfc.nasa.gov/session/1291D6CC-844D-11EA-8E98-595979988AF1/76EA5316-9B12-11EA-986C-D3E44B67C885/76EAFC62-9B12-11EA-986C-D3E44B67C885/g4.timeAvgMap.MYD08_D3_6_1_AOD_550_Dark_Target_Deep_Blue_Combined_Mean.{}{:02d}{:02d}'.format(year,month,day)+'-{}{:02d}{:02d}'.format(year,month,day)+'.180W_90S_180E_90N.nc')
#
#day=31#get the 31st
#for month in [1,3,5,7,8,10,12]:
#    webbrowser.get(chrome_path).open('https://giovanni.gsfc.nasa.gov/session/1291D6CC-844D-11EA-8E98-595979988AF1/76EA5316-9B12-11EA-986C-D3E44B67C885/76EAFC62-9B12-11EA-986C-D3E44B67C885/g4.timeAvgMap.MYD08_D3_6_1_AOD_550_Dark_Target_Deep_Blue_Combined_Mean.{}{:02d}{:02d}'.format(year,month,day)+'-{}{:02d}{:02d}'.format(year,month,day)+'.180W_90S_180E_90N.nc')
